### ISSUE TITLE
Can we disable scroll wheel capture on the map?

### ISSUE THREAD

**Issue by jgwhite** [emberlondon/emberlondon.github.io#7]

**Comment by pootsbook** [comment]
@jgwhite Turns out this is almost impossible to do without a hack. See this [Google Maps Help Forum Discussion](https://productforums.google.com/forum/#!topic/maps/9eQvCPWAJwE). The hack proposed in [this StackOverflow question](http://stackoverflow.com/questions/21992498/is-it-possible-to-disable-mouse-scroll-wheel-zoom-on-embedded-google-maps) involves a masking `div` hiding pointer-events from the underlying `iframe`. Clicking on the `div` disables the mask allowing pointer-events to access the `iframe` again.

If you're happy with that solution then I'll give it a go, but wanted to check with you first.

**Comment by jgwhite** [comment]
@pootsbook could we insert the map using the google.maps javascript API rather than an iframe (or whatever it is we currently do)?

**Comment by pootsbook** [comment]
Yes, that's a much better solution. It's a little more involved so it'll be a few days before I get around to it. It requires an [API Key](https://developers.google.com/maps/documentation/javascript/tutorial#api_key) which could be limited to the referrer, `emberlondon.com`.

**Comment by jgwhite** [comment]
@pootsbook thanks for looking into this. We really appreciate it!

I’ll generate an API key for the organisaiton.

**Comment by jgwhite** [comment]
Closed by #9
